import connectDB from "@/lib/db";
import Article from "@/models/Article";
import Tag from "@/models/Tag";
import Category from "@/models/Category";
import User from "@/models/User";
import UsedKeyword from "@/models/UsedKeyword";
import slugify from "slugify";
import { uploadFromUrl } from "@/lib/services/cloudinaryService";

/**
 * Persistence layer for AI-generated blog posts
 */
export async function saveBlog(blogData: any) {
  const { 
    topic, 
    content, 
    slug: initialSlug, 
    meta_description, 
    tags, 
    category: categoryName,
    featured_image 
  } = blogData;

  await connectDB();

  // 1. Resolve Tags
  const tagIds = await Promise.all(
    (tags || []).slice(0, 5).map(async (tagName: string) => {
      const tagSlug = slugify(tagName, { lower: true, strict: true });
      const tag = await Tag.findOneAndUpdate(
        { slug: tagSlug },
        { name: tagName, slug: tagSlug },
        { upsert: true, returnDocument: 'after' }
      );
      return tag._id;
    })
  );

  // 2. Resolve Category (using NewsSphare schema fields)
  let category = await Category.findOne({ 
    $or: [
      { name: new RegExp(`^${categoryName}$`, 'i') }, 
      { slug: slugify(categoryName || "Uncategorized", { lower: true, strict: true }) }
    ] 
  });
  
  if (!category) {
    // Fallback to "AI Generated"
    category = await Category.findOneAndUpdate(
      { slug: "ai-generated" },
      { 
        name: "AI Generated", 
        slug: "ai-generated",
        description: "Articles automatically generated by AI.",
        color: "#6366f1"
      },
      { upsert: true, returnDocument: 'after' }
    );
  }

  // 3. Default Author
  let author = await User.findOne({ role: "admin" });
  if (!author) author = await User.findOne({});
  if (!author) {
    // If absolutely no user exists, we can't save. 
    // This usually only happens on a brand new DB without any registration.
    console.warn("[BlogService] No users found in database. Cannot assign author.");
    throw new Error("No user found in database to assign as author. Please register an admin user first.");
  }
  if (!category) throw new Error("Failed to resolve category");

  // 4. Unique Slug
  let finalSlug = initialSlug || slugify(topic, { lower: true, strict: true });
  const existing = await Article.findOne({ slug: finalSlug });
  if (existing) finalSlug = `${finalSlug}-${Date.now().toString().slice(-4)}`;

  // 5. Create Excerpt (strip HTML and truncate)
  const plainText = content.replace(/<[^>]*>?/gm, '');
  const excerpt = plainText.slice(0, 250) + (plainText.length > 250 ? '...' : '');

  // 6. Upload image to Cloudinary for permanent hosting
  let activeImageUrl = featured_image;
  if (activeImageUrl) {
    activeImageUrl = await uploadFromUrl(activeImageUrl, `newsphere/articles/${finalSlug}`);
  }

  // 7. Create Article (matching NewsSphare.Article schema)
  const article = await Article.create({
    title: topic,
    slug: finalSlug,
    excerpt: excerpt,
    content: content,
    featuredImage: activeImageUrl || "https://picsum.photos/seed/" + finalSlug + "/1200/630",
    featuredImageAlt: topic,
    author: author._id,
    category: category._id,
    tags: tagIds,
    status: "published", 
    publishedAt: new Date(),
    isFeatured: true, // Make AI articles featured to ensure visibility
    isTrending: true, // Also set trending for testing visibility
    views: Math.floor(Math.random() * 50),
    readingTime: Math.max(1, Math.ceil(plainText.split(/\s+/).length / 200)),
    metaTitle: topic.slice(0, 60),
    metaDescription: (meta_description || excerpt).slice(0, 160)
  });

  // Mark keyword used
  await markKeywordUsed(topic, 'success', article._id);
  return article;
}

export async function isKeywordUsed(keyword: string): Promise<boolean> {
  await connectDB();
  const lower = keyword.toLowerCase().trim();
  const used = await UsedKeyword.findOne({ keyword: lower });
  if (used) return true;
  
  const existing = await Article.findOne({ title: new RegExp(`^${lower}$`, 'i') });
  return !!existing;
}

export async function markKeywordUsed(keyword: string, status: 'success' | 'failed' = 'success', postId: any = null) {
  await connectDB();
  const lower = keyword.toLowerCase().trim();
  await UsedKeyword.findOneAndUpdate(
    { keyword: lower },
    { 
      keyword: lower, 
      slug: slugify(lower, { lower: true, strict: true }), 
      status, 
      postId, 
      usedAt: new Date() 
    },
    { upsert: true, returnDocument: 'after' }
  );
}
